tunnel: 072a6293-1edf-4c7e-b9b2-bcc59abfa77b
credentials-file: /Users/nakasyou/.cloudflared/072a6293-1edf-4c7e-b9b2-bcc59abfa77b.json

ingress:
  - hostname: betterzeriya.nakasyou.how
    service: http://127.0.0.1:3000
  - hostname: nextcloud.nakasyou.how
    service: http://127.0.0.1:8080
    originRequest:
      noHappyEyeballs: true
      keepAliveConnections: 1000
      keepAliveTimeout: 10m
      tcpKeepAlive: 30s
  - hostname: litellm.nakasyou.how
    service: http://127.0.0.1:4000
    originRequest:
      connectTimeout: 5m
      tlsTimeout: 30s
      tcpKeepAlive: 30s
      keepAliveConnections: 50
  - hostname: csbie.nakasyou.how
    service: http://127.0.0.1:18787
  - hostname: status.nakasyou.how
    service: http://127.0.0.1:3001
  - service: http_status:404
