[Appearance]
style=kvantum
icon_theme=MaterialDolphin
custom_palette=false
standard_dialogs=default

[Fonts]
general="Noto Sans,10,-1,5,50,0,0,0,0,0"
fixed="Noto Sans Mono,10,-1,5,50,0,0,0,0,0"

[Interface]
activate_item_on_single_click=0
buttonbox_layout=0
dialog_buttons_have_icons=0
menus_have_icons=false
toolbutton_style=0
underline_shortcut=0
